CREATE TABLE products
(
    id               INTEGER PRIMARY KEY,
    code             TEXT NOT NULL,
    name             TEXT NOT NULL,
    description      TEXT,
    image            TEXT,
    price            REAL,
    category         TEXT,
    quantity         INTEGER,
    inventory_status TEXT,
    rating           INTEGER
);
INSERT INTO product (id, code, name, description, image, price, category, quantity, inventory_status, rating)
VALUES (1000, 'f230fh0g3', 'Bamboo Watch', 'Product Description', 'bamboo-watch.jpg', 65, 'Accessories', 24, 'INSTOCK',
        5),
       (1001, 'nvklal433', 'Black Watch', 'Product Description', 'black-watch.jpg', 72, 'Accessories', 61, 'INSTOCK',
        4),
       (1002, 'zz21cz3c1', 'Blue Band', 'Product Description', 'blue-band.jpg', 79, 'Fitness', 2, 'LOWSTOCK', 3),
       (1003, '244wgerg2', 'Blue T-Shirt', 'Product Description', 'blue-t-shirt.jpg', 29, 'Clothing', 25, 'INSTOCK', 5),
       (1004, 'h456wer53', 'Bracelet', 'Product Description', 'bracelet.jpg', 15, 'Accessories', 73, 'INSTOCK', 4),
       (1005, 'av2231fwg', 'Brown Purse', 'Product Description', 'brown-purse.jpg', 120, 'Accessories', 0, 'OUTOFSTOCK',
        4),
       (1006, 'bib36pfvm', 'Chakra Bracelet', 'Product Description', 'chakra-bracelet.jpg', 32, 'Accessories', 5,
        'LOWSTOCK', 3),
       (1007, 'mbvjkgip5', 'Galaxy Earrings', 'Product Description', 'galaxy-earrings.jpg', 34, 'Accessories', 23,
        'INSTOCK', 5),
       (1008, 'vbb124btr', 'Game Controller', 'Product Description', 'game-controller.jpg', 99, 'Electronics', 2,
        'LOWSTOCK', 4),
       (1009, 'cm230f032', 'Gaming Set', 'Product Description', 'gaming-set.jpg', 299, 'Electronics', 63, 'INSTOCK', 3),
       (1010, 'plb34234v', 'Gold Phone Case', 'Product Description', 'gold-phone-case.jpg', 24, 'Accessories', 0,
        'OUTOFSTOCK', 4),
       (1011, '4920nnc2d', 'Green Earbuds', 'Product Description', 'green-earbuds.jpg', 89, 'Electronics', 23,
        'INSTOCK', 4),
       (1012, '250vm23cc', 'Green T-Shirt', 'Product Description', 'green-t-shirt.jpg', 49, 'Clothing', 74, 'INSTOCK',
        5),
       (1013, 'fldsmn31b', 'Grey T-Shirt', 'Product Description', 'grey-t-shirt.jpg', 48, 'Clothing', 0, 'OUTOFSTOCK',
        3),
       (1014, 'waas1x2as', 'Headphones', 'Product Description', 'headphones.jpg', 175, 'Electronics', 8, 'LOWSTOCK', 5),
       (1015, 'vb34btbg5', 'Light Green T-Shirt', 'Product Description', 'light-green-t-shirt.jpg', 49, 'Clothing', 34,
        'INSTOCK', 4),
       (1016, 'k8l6j58jl', 'Lime Band', 'Product Description', 'lime-band.jpg', 79, 'Fitness', 12, 'INSTOCK', 3),
       (1017, 'v435nn85n', 'Mini Speakers', 'Product Description', 'mini-speakers.jpg', 85, 'Clothing', 42, 'INSTOCK',
        4),
       (1018, '09zx9c0zc', 'Painted Phone Case', 'Product Description', 'painted-phone-case.jpg', 56, 'Accessories', 41,
        'INSTOCK', 5),
       (1019, 'mnb5mb2m5', 'Pink Band', 'Product Description', 'pink-band.jpg', 79, 'Fitness', 63, 'INSTOCK', 4),
       (1020, 'r23fwf2w3', 'Pink Purse', 'Product Description', 'pink-purse.jpg', 110, 'Accessories', 0, 'OUTOFSTOCK',
        4),
       (1021, 'pxpzczo23', 'Purple Band', 'Product Description', 'purple-band.jpg', 79, 'Fitness', 6, 'LOWSTOCK', 3),
       (1022, '2c42cb5cb', 'Purple Gemstone Necklace', 'Product Description', 'purple-gemstone-necklace.jpg', 45,
        'Accessories', 62, 'INSTOCK', 4),
       (1023, '5k43kkk23', 'Purple T-Shirt', 'Product Description', 'purple-t-shirt.jpg', 49, 'Clothing', 2, 'LOWSTOCK',
        5),
       (1024, 'lm2tny2k4', 'Shoes', 'Product Description', 'shoes.jpg', 64, 'Clothing', 0, 'INSTOCK', 4),
       (1025, 'nbm5mv45n', 'Sneakers', 'Product Description', 'sneakers.jpg', 78, 'Clothing', 52, 'INSTOCK', 4),
       (1026, 'zx23zc42c', 'Teal T-Shirt', 'Product Description', 'teal-t-shirt.jpg', 49, 'Clothing', 3, 'LOWSTOCK', 3),
       (1027, 'acvx872gc', 'Yellow Earbuds', 'Product Description', 'yellow-earbuds.jpg', 89, 'Electronics', 35,
        'INSTOCK', 3),
       (1028, 'tx125ck42', 'Yoga Mat', 'Product Description', 'yoga-mat.jpg', 20, 'Fitness', 15, 'INSTOCK', 5),
       (1029, 'gwuby345v', 'Yoga Set', 'Product Description', 'yoga-set.jpg', 20, 'Fitness', 25, 'INSTOCK', 5),
       (1030, 'abcd1234', 'Red Watch', 'Product Description', 'red-watch.jpg', 75, 'Accessories', 10, 'INSTOCK', 4),
       (1031, 'efgh5678', 'Silver Necklace', 'Product Description', 'silver-necklace.jpg', 150, 'Accessories', 0,
        'OUTOFSTOCK', 5),
       (1032, 'ijkl9101', 'Gold Ring', 'Product Description', 'gold-ring.jpg', 200, 'Accessories', 5, 'LOWSTOCK', 5),
       (1033, 'mnop1121', 'Smartphone', 'Product Description', 'smartphone.jpg', 999, 'Electronics', 20, 'INSTOCK', 5),
       (1034, 'qrst3141', 'Laptop', 'Product Description', 'laptop.jpg', 1200, 'Electronics', 15, 'INSTOCK', 4),
       (1035, 'uvwx5161', 'Tablet', 'Product Description', 'tablet.jpg', 350, 'Electronics', 25, 'INSTOCK', 4),
       (1036, 'yzab7181', 'Wireless Mouse', 'Product Description', 'wireless-mouse.jpg', 50, 'Electronics', 60,
        'INSTOCK', 4),
       (1037, 'cdab9201', 'Wireless Keyboard', 'Product Description', 'wireless-keyboard.jpg', 75, 'Electronics', 45,
        'INSTOCK', 4),
       (1038, 'efgh1222', 'Monitor', 'Product Description', 'monitor.jpg', 200, 'Electronics', 18, 'INSTOCK', 4),
       (1039, 'ijkl3242', 'Printer', 'Product Description', 'printer.jpg', 150, 'Electronics', 5, 'LOWSTOCK', 3),
       (1040, 'mnop5262', 'Scanner', 'Product Description', 'scanner.jpg', 125, 'Electronics', 8, 'LOWSTOCK', 3),
       (1041, 'qrst7282', 'Desk Lamp', 'Product Description', 'desk-lamp.jpg', 45, 'Furniture', 30, 'INSTOCK', 4),
       (1042, 'uvwx9302', 'Office Chair', 'Product Description', 'office-chair.jpg', 120, 'Furniture', 10, 'INSTOCK',
        5),
       (1043, 'yzab1422', 'Bookshelf', 'Product Description', 'bookshelf.jpg', 85, 'Furniture', 5, 'LOWSTOCK', 4),
       (1044, 'cdab3442', 'Sofa', 'Product Description', 'sofa.jpg', 750, 'Furniture', 2, 'LOWSTOCK', 5),
       (1045, 'efgh5462', 'Coffee Table', 'Product Description', 'coffee-table.jpg', 100, 'Furniture', 20, 'INSTOCK',
        4),
       (1046, 'ijkl7482', 'Dining Table', 'Product Description', 'dining-table.jpg', 300, 'Furniture', 7, 'LOWSTOCK',
        5),
       (1047, 'mnop9502', 'Dining Chair', 'Product Description', 'dining-chair.jpg', 75, 'Furniture', 25, 'INSTOCK', 4),
       (1048, 'qrst1522', 'Bed', 'Product Description', 'bed.jpg', 500, 'Furniture', 4, 'LOWSTOCK', 5),
       (1049, 'uvwx3542', 'Wardrobe', 'Product Description', 'wardrobe.jpg', 450, 'Furniture', 6, 'LOWSTOCK', 5),
       (1050, 'yzab5562', 'Dresser', 'Product Description', 'dresser.jpg', 300, 'Furniture', 12, 'INSTOCK', 4),
       (1051, 'cdab7582', 'Nightstand', 'Product Description', 'nightstand.jpg', 85, 'Furniture', 15, 'INSTOCK', 4),
       (1052, 'efgh9602', 'Blender', 'Product Description', 'blender.jpg', 50, 'Appliances', 25, 'INSTOCK', 4),
       (1053, 'ijkl1622', 'Microwave', 'Product Description', 'microwave.jpg', 150, 'Appliances', 8, 'LOWSTOCK', 4),
       (1054, 'mnop3642', 'Toaster', 'Product Description', 'toaster.jpg', 30, 'Appliances', 50, 'INSTOCK', 3),
       (1055, 'qrst5662', 'Refrigerator', 'Product Description', 'refrigerator.jpg', 900, 'Appliances', 3, 'LOWSTOCK',
        5),
       (1056, 'uvwx7682', 'Washing Machine', 'Product Description', 'washing-machine.jpg', 600, 'Appliances', 7,
        'LOWSTOCK', 5),
       (1057, 'yzab9702', 'Dryer', 'Product Description', 'dryer.jpg', 550, 'Appliances', 10, 'INSTOCK', 4),
       (1058, 'cdab1722', 'Dishwasher', 'Product Description', 'dishwasher.jpg', 700, 'Appliances', 5, 'LOWSTOCK', 5),
       (1059, 'efgh3742', 'Air Conditioner', 'Product Description', 'air-conditioner.jpg', 1200, 'Appliances', 2,
        'LOWSTOCK', 5),
       (1060, 'ijkl5762', 'Heater', 'Product Description', 'heater.jpg', 250, 'Appliances', 20, 'INSTOCK', 4),
       (1061, 'mnop7782', 'Ceiling Fan', 'Product Description', 'ceiling-fan.jpg', 150, 'Appliances', 15, 'INSTOCK', 4),
       (1062, 'qrst9802', 'Vacuum Cleaner', 'Product Description', 'vacuum-cleaner.jpg', 300, 'Appliances', 12,
        'INSTOCK', 4),
       (1063, 'uvwx1922', 'Iron', 'Product Description', 'iron.jpg', 40, 'Appliances', 40, 'INSTOCK', 3),
       (1064, 'yzab3942', 'Toaster Oven', 'Product Description', 'toaster-oven.jpg', 80, 'Appliances', 25, 'INSTOCK',
        4),
       (1065, 'cdab5962', 'Mixer', 'Product Description', 'mixer.jpg', 120, 'Appliances', 18, 'INSTOCK', 5),
       (1066, 'efgh7982', 'Food Processor', 'Product Description', 'food-processor.jpg', 150, 'Appliances', 8,
        'LOWSTOCK', 4),
       (1067, 'ijkl1002', 'Slow Cooker', 'Product Description', 'slow-cooker.jpg', 75, 'Appliances', 12, 'INSTOCK', 4),
       (1068, 'mnop2022', 'Rice Cooker', 'Product Description', 'rice-cooker.jpg', 60, 'Appliances', 20, 'INSTOCK', 4),
       (1069, 'qrst4042', 'Electric Kettle', 'Product Description', 'electric-kettle.jpg', 45, 'Appliances', 30,
        'INSTOCK', 4),
       (1070, 'uvwx6062', 'Hair Dryer', 'Product Description', 'hair-dryer.jpg', 40, 'Appliances', 25, 'INSTOCK', 3),
       (1071, 'yzab8082', 'Curling Iron', 'Product Description', 'curling-iron.jpg', 35, 'Appliances', 22, 'INSTOCK',
        3),
       (1072, 'cdab1123', 'Hair Straightener', 'Product Description', 'hair-straightener.jpg', 50, 'Appliances', 18,
        'INSTOCK', 4),
       (1073, 'efgh3143', 'Shaver', 'Product Description', 'shaver.jpg', 60, 'Appliances', 35, 'INSTOCK', 4),
       (1074, 'ijkl5163', 'Electric Toothbrush', 'Product Description', 'electric-toothbrush.jpg', 80, 'Appliances', 15,
        'INSTOCK', 5),
       (1075, 'mnop7183', 'Steam Iron', 'Product Description', 'steam-iron.jpg', 65, 'Appliances', 12, 'INSTOCK', 4),
       (1076, 'qrst9203', 'Air Purifier', 'Product Description', 'air-purifier.jpg', 200, 'Appliances', 10, 'INSTOCK',
        5),
       (1077, 'uvwx1223', 'Water Filter', 'Product Description', 'water-filter.jpg', 90, 'Appliances', 20, 'INSTOCK',
        4);
