CREATE TABLE products
(
    id               INTEGER PRIMARY KEY,
    code             TEXT NOT NULL,
    name             TEXT NOT NULL,
    description      TEXT,
    image            TEXT,
    price            REAL,
    category         TEXT,
    quantity         INTEGER,
    inventory_status TEXT,
    rating           INTEGER
);
INSERT INTO products (id, code, name, description, image, price, category, quantity, inventory_status, rating)
VALUES (1000, 'f230fh0g3', 'Bamboo Watch', 'Product Description', 'https://gebelesebeti.ge/front/asset/img/default-product.png', 65, 'Accessories', 24, 'INSTOCK',
        5),
       (1001, 'nvklal433', 'Black Watch', 'Product Description', 'https://gebelesebeti.ge/front/asset/img/default-product.png', 72, 'Accessories', 61, 'INSTOCK',
        4),
       (1002, 'zz21cz3c1', 'Blue Band', 'Product Description', 'https://gebelesebeti.ge/front/asset/img/default-product.png', 79, 'Fitness', 2, 'LOWSTOCK', 3),
       (1003, '244wgerg2', 'Blue T-Shirt', 'Product Description', 'https://gebelesebeti.ge/front/asset/img/default-product.png', 29, 'Clothing', 25, 'INSTOCK', 5),
       (1004, 'h456wer53', 'Bracelet', 'Product Description', 'https://gebelesebeti.ge/front/asset/img/default-product.png', 15, 'Accessories', 73, 'INSTOCK', 4),
       (1005, 'av2231fwg', 'Brown Purse', 'Product Description', 'https://gebelesebeti.ge/front/asset/img/default-product.png', 120, 'Accessories', 0, 'OUTOFSTOCK',
        4),
       (1006, 'bib36pfvm', 'Chakra Bracelet', 'Product Description', 'https://gebelesebeti.ge/front/asset/img/default-product.png', 32, 'Accessories', 5,
        'LOWSTOCK', 3),
       (1007, 'mbvjkgip5', 'Galaxy Earrings', 'Product Description', 'https://gebelesebeti.ge/front/asset/img/default-product.png', 34, 'Accessories', 23,
        'INSTOCK', 5),
       (1008, 'vbb124btr', 'Game Controller', 'Product Description', 'https://gebelesebeti.ge/front/asset/img/default-product.png', 99, 'Electronics', 2,
        'LOWSTOCK', 4),
       (1009, 'cm230f032', 'Gaming Set', 'Product Description', 'https://gebelesebeti.ge/front/asset/img/default-product.png', 299, 'Electronics', 63, 'INSTOCK', 3),
       (1010, 'plb34234v', 'Gold Phone Case', 'Product Description', 'https://gebelesebeti.ge/front/asset/img/default-product.png', 24, 'Accessories', 0,
        'OUTOFSTOCK', 4),
       (1011, '4920nnc2d', 'Green Earbuds', 'Product Description', 'https://gebelesebeti.ge/front/asset/img/default-product.png', 89, 'Electronics', 23,
        'INSTOCK', 4),
       (1012, '250vm23cc', 'Green T-Shirt', 'Product Description', 'https://gebelesebeti.ge/front/asset/img/default-product.png', 49, 'Clothing', 74, 'INSTOCK',
        5),
       (1013, 'fldsmn31b', 'Grey T-Shirt', 'Product Description', 'https://gebelesebeti.ge/front/asset/img/default-product.png', 48, 'Clothing', 0, 'OUTOFSTOCK',
        3),
       (1014, 'waas1x2as', 'Headphones', 'Product Description', 'https://gebelesebeti.ge/front/asset/img/default-product.png', 175, 'Electronics', 8, 'LOWSTOCK', 5),
       (1015, 'vb34btbg5', 'Light Green T-Shirt', 'Product Description', 'https://gebelesebeti.ge/front/asset/img/default-product.png', 49, 'Clothing', 34,
        'INSTOCK', 4),
       (1016, 'k8l6j58jl', 'Lime Band', 'Product Description', 'https://gebelesebeti.ge/front/asset/img/default-product.png', 79, 'Fitness', 12, 'INSTOCK', 3),
       (1017, 'v435nn85n', 'Mini Speakers', 'Product Description', 'https://gebelesebeti.ge/front/asset/img/default-product.png', 85, 'Clothing', 42, 'INSTOCK',
        4),
       (1018, '09zx9c0zc', 'Painted Phone Case', 'Product Description', 'https://gebelesebeti.ge/front/asset/img/default-product.png', 56, 'Accessories', 41,
        'INSTOCK', 5),
       (1019, 'mnb5mb2m5', 'Pink Band', 'Product Description', 'https://gebelesebeti.ge/front/asset/img/default-product.png', 79, 'Fitness', 63, 'INSTOCK', 4),
       (1020, 'r23fwf2w3', 'Pink Purse', 'Product Description', 'https://gebelesebeti.ge/front/asset/img/default-product.png', 110, 'Accessories', 0, 'OUTOFSTOCK',
        4),
       (1021, 'pxpzczo23', 'Purple Band', 'Product Description', 'https://gebelesebeti.ge/front/asset/img/default-product.png', 79, 'Fitness', 6, 'LOWSTOCK', 3),
       (1022, '2c42cb5cb', 'Purple Gemstone Necklace', 'Product Description', 'https://gebelesebeti.ge/front/asset/img/default-product.png', 45,
        'Accessories', 62, 'INSTOCK', 4),
       (1023, '5k43kkk23', 'Purple T-Shirt', 'Product Description', 'https://gebelesebeti.ge/front/asset/img/default-product.png', 49, 'Clothing', 2, 'LOWSTOCK',
        5),
       (1024, 'lm2tny2k4', 'Shoes', 'Product Description', 'https://gebelesebeti.ge/front/asset/img/default-product.png', 64, 'Clothing', 0, 'INSTOCK', 4),
       (1025, 'nbm5mv45n', 'Sneakers', 'Product Description', 'https://gebelesebeti.ge/front/asset/img/default-product.png', 78, 'Clothing', 52, 'INSTOCK', 4),
       (1026, 'zx23zc42c', 'Teal T-Shirt', 'Product Description', 'https://gebelesebeti.ge/front/asset/img/default-product.png', 49, 'Clothing', 3, 'LOWSTOCK', 3),
       (1027, 'acvx872gc', 'Yellow Earbuds', 'Product Description', 'https://gebelesebeti.ge/front/asset/img/default-product.png', 89, 'Electronics', 35,
        'INSTOCK', 3),
       (1028, 'tx125ck42', 'Yoga Mat', 'Product Description', 'https://gebelesebeti.ge/front/asset/img/default-product.png', 20, 'Fitness', 15, 'INSTOCK', 5),
       (1029, 'gwuby345v', 'Yoga Set', 'Product Description', 'https://gebelesebeti.ge/front/asset/img/default-product.png', 20, 'Fitness', 25, 'INSTOCK', 5),
       (1030, 'abcd1234', 'Red Watch', 'Product Description', 'https://gebelesebeti.ge/front/asset/img/default-product.png', 75, 'Accessories', 10, 'INSTOCK', 4),
       (1031, 'efgh5678', 'Silver Necklace', 'Product Description', 'https://gebelesebeti.ge/front/asset/img/default-product.png', 150, 'Accessories', 0,
        'OUTOFSTOCK', 5),
       (1032, 'ijkl9101', 'Gold Ring', 'Product Description', 'https://gebelesebeti.ge/front/asset/img/default-product.png', 200, 'Accessories', 5, 'LOWSTOCK', 5),
       (1033, 'mnop1121', 'Smartphone', 'Product Description', 'https://gebelesebeti.ge/front/asset/img/default-product.png', 999, 'Electronics', 20, 'INSTOCK', 5),
       (1034, 'qrst3141', 'Laptop', 'Product Description', 'https://gebelesebeti.ge/front/asset/img/default-product.png', 1200, 'Electronics', 15, 'INSTOCK', 4),
       (1035, 'uvwx5161', 'Tablet', 'Product Description', 'https://gebelesebeti.ge/front/asset/img/default-product.png', 350, 'Electronics', 25, 'INSTOCK', 4),
       (1036, 'yzab7181', 'Wireless Mouse', 'Product Description', 'https://gebelesebeti.ge/front/asset/img/default-product.png', 50, 'Electronics', 60,
        'INSTOCK', 4),
       (1037, 'cdab9201', 'Wireless Keyboard', 'Product Description', 'https://gebelesebeti.ge/front/asset/img/default-product.png', 75, 'Electronics', 45,
        'INSTOCK', 4),
       (1038, 'efgh1222', 'Monitor', 'Product Description', 'https://gebelesebeti.ge/front/asset/img/default-product.png', 200, 'Electronics', 18, 'INSTOCK', 4),
       (1039, 'ijkl3242', 'Printer', 'Product Description', 'https://gebelesebeti.ge/front/asset/img/default-product.png', 150, 'Electronics', 5, 'LOWSTOCK', 3),
       (1040, 'mnop5262', 'Scanner', 'Product Description', 'https://gebelesebeti.ge/front/asset/img/default-product.png', 125, 'Electronics', 8, 'LOWSTOCK', 3),
       (1041, 'qrst7282', 'Desk Lamp', 'Product Description', 'https://gebelesebeti.ge/front/asset/img/default-product.png', 45, 'Furniture', 30, 'INSTOCK', 4),
       (1042, 'uvwx9302', 'Office Chair', 'Product Description', 'https://gebelesebeti.ge/front/asset/img/default-product.png', 120, 'Furniture', 10, 'INSTOCK',
        5),
       (1043, 'yzab1422', 'Bookshelf', 'Product Description', 'https://gebelesebeti.ge/front/asset/img/default-product.png', 85, 'Furniture', 5, 'LOWSTOCK', 4),
       (1044, 'cdab3442', 'Sofa', 'Product Description', 'https://gebelesebeti.ge/front/asset/img/default-product.png', 750, 'Furniture', 2, 'LOWSTOCK', 5),
       (1045, 'efgh5462', 'Coffee Table', 'Product Description', 'https://gebelesebeti.ge/front/asset/img/default-product.png', 100, 'Furniture', 20, 'INSTOCK',
        4),
       (1046, 'ijkl7482', 'Dining Table', 'Product Description', 'https://gebelesebeti.ge/front/asset/img/default-product.png', 300, 'Furniture', 7, 'LOWSTOCK',
        5),
       (1047, 'mnop9502', 'Dining Chair', 'Product Description', 'https://gebelesebeti.ge/front/asset/img/default-product.png', 75, 'Furniture', 25, 'INSTOCK', 4),
       (1048, 'qrst1522', 'Bed', 'Product Description', 'https://gebelesebeti.ge/front/asset/img/default-product.png', 500, 'Furniture', 4, 'LOWSTOCK', 5),
       (1049, 'uvwx3542', 'Wardrobe', 'Product Description', 'https://gebelesebeti.ge/front/asset/img/default-product.png', 450, 'Furniture', 6, 'LOWSTOCK', 5),
       (1050, 'yzab5562', 'Dresser', 'Product Description', 'https://gebelesebeti.ge/front/asset/img/default-product.png', 300, 'Furniture', 12, 'INSTOCK', 4),
       (1051, 'cdab7582', 'Nightstand', 'Product Description', 'https://gebelesebeti.ge/front/asset/img/default-product.png', 85, 'Furniture', 15, 'INSTOCK', 4),
       (1052, 'efgh9602', 'Blender', 'Product Description', 'https://gebelesebeti.ge/front/asset/img/default-product.png', 50, 'Appliances', 25, 'INSTOCK', 4),
       (1053, 'ijkl1622', 'Microwave', 'Product Description', 'https://gebelesebeti.ge/front/asset/img/default-product.png', 150, 'Appliances', 8, 'LOWSTOCK', 4),
       (1054, 'mnop3642', 'Toaster', 'Product Description', 'https://gebelesebeti.ge/front/asset/img/default-product.png', 30, 'Appliances', 50, 'INSTOCK', 3),
       (1055, 'qrst5662', 'Refrigerator', 'Product Description', 'https://gebelesebeti.ge/front/asset/img/default-product.png', 900, 'Appliances', 3, 'LOWSTOCK',
        5),
       (1056, 'uvwx7682', 'Washing Machine', 'Product Description', 'https://gebelesebeti.ge/front/asset/img/default-product.png', 600, 'Appliances', 7,
        'LOWSTOCK', 5),
       (1057, 'yzab9702', 'Dryer', 'Product Description', 'https://gebelesebeti.ge/front/asset/img/default-product.png', 550, 'Appliances', 10, 'INSTOCK', 4),
       (1058, 'cdab1722', 'Dishwasher', 'Product Description', 'https://gebelesebeti.ge/front/asset/img/default-product.png', 700, 'Appliances', 5, 'LOWSTOCK', 5),
       (1059, 'efgh3742', 'Air Conditioner', 'Product Description', 'https://gebelesebeti.ge/front/asset/img/default-product.png', 1200, 'Appliances', 2,
        'LOWSTOCK', 5),
       (1060, 'ijkl5762', 'Heater', 'Product Description', 'https://gebelesebeti.ge/front/asset/img/default-product.png', 250, 'Appliances', 20, 'INSTOCK', 4),
       (1061, 'mnop7782', 'Ceiling Fan', 'Product Description', 'https://gebelesebeti.ge/front/asset/img/default-product.png', 150, 'Appliances', 15, 'INSTOCK', 4),
       (1062, 'qrst9802', 'Vacuum Cleaner', 'Product Description', 'https://gebelesebeti.ge/front/asset/img/default-product.png', 300, 'Appliances', 12,
        'INSTOCK', 4),
       (1063, 'uvwx1922', 'Iron', 'Product Description', 'https://gebelesebeti.ge/front/asset/img/default-product.png', 40, 'Appliances', 40, 'INSTOCK', 3),
       (1064, 'yzab3942', 'Toaster Oven', 'Product Description', 'https://gebelesebeti.ge/front/asset/img/default-product.png', 80, 'Appliances', 25, 'INSTOCK',
        4),
       (1065, 'cdab5962', 'Mixer', 'Product Description', 'https://gebelesebeti.ge/front/asset/img/default-product.png', 120, 'Appliances', 18, 'INSTOCK', 5),
       (1066, 'efgh7982', 'Food Processor', 'Product Description', 'https://gebelesebeti.ge/front/asset/img/default-product.png', 150, 'Appliances', 8,
        'LOWSTOCK', 4),
       (1067, 'ijkl1002', 'Slow Cooker', 'Product Description', 'https://gebelesebeti.ge/front/asset/img/default-product.png', 75, 'Appliances', 12, 'INSTOCK', 4),
       (1068, 'mnop2022', 'Rice Cooker', 'Product Description', 'https://gebelesebeti.ge/front/asset/img/default-product.png', 60, 'Appliances', 20, 'INSTOCK', 4),
       (1069, 'qrst4042', 'Electric Kettle', 'Product Description', 'https://gebelesebeti.ge/front/asset/img/default-product.png', 45, 'Appliances', 30,
        'INSTOCK', 4),
       (1070, 'uvwx6062', 'Hair Dryer', 'Product Description', 'https://gebelesebeti.ge/front/asset/img/default-product.png', 40, 'Appliances', 25, 'INSTOCK', 3),
       (1071, 'yzab8082', 'Curling Iron', 'Product Description', 'https://gebelesebeti.ge/front/asset/img/default-product.png', 35, 'Appliances', 22, 'INSTOCK',
        3),
       (1072, 'cdab1123', 'Hair Straightener', 'Product Description', 'https://gebelesebeti.ge/front/asset/img/default-product.png', 50, 'Appliances', 18,
        'INSTOCK', 4),
       (1073, 'efgh3143', 'Shaver', 'Product Description', 'https://gebelesebeti.ge/front/asset/img/default-product.png', 60, 'Appliances', 35, 'INSTOCK', 4),
       (1074, 'ijkl5163', 'Electric Toothbrush', 'Product Description', 'https://gebelesebeti.ge/front/asset/img/default-product.png', 80, 'Appliances', 15,
        'INSTOCK', 5),
       (1075, 'mnop7183', 'Steam Iron', 'Product Description', 'https://gebelesebeti.ge/front/asset/img/default-product.png', 65, 'Appliances', 12, 'INSTOCK', 4),
       (1076, 'qrst9203', 'Air Purifier', 'Product Description', 'https://gebelesebeti.ge/front/asset/img/default-product.png', 200, 'Appliances', 10, 'INSTOCK',
        5),
       (1077, 'uvwx1223', 'Water Filter', 'Product Description', 'https://gebelesebeti.ge/front/asset/img/default-product.png', 90, 'Appliances', 20, 'INSTOCK',
        4);
