CREATE TABLE products
(
    id               INTEGER PRIMARY KEY,
    code             TEXT NOT NULL,
    name             TEXT NOT NULL,
    description      TEXT,
    image            TEXT,
    price            REAL,
    category         TEXT,
    quantity         INTEGER,
    inventory_status TEXT,
    rating           INTEGER
);
INSERT INTO products (id, code, name, description, image, price, category, quantity, inventory_status, rating)
VALUES (1000, 'AcBa-9834', 'Bamboo Watch',
        'This Bamboo Watch is an elegant and eco-friendly choice made from sustainable materials.',
        'https://gebelesebeti.ge/front/asset/img/default-product.png', 65, 'Accessories', 24, 'INSTOCK', 5),
       (1001, 'AcBl-2378', 'Black Watch',
        'The Black Watch is a classic timepiece that adds sophistication to any outfit.',
        'https://gebelesebeti.ge/front/asset/img/default-product.png', 72, 'Accessories', 61, 'INSTOCK', 4),
       (1002, 'FiBl-5923', 'Blue Band', 'The Blue Band is a durable and stylish accessory for your fitness activities.',
        'https://gebelesebeti.ge/front/asset/img/default-product.png', 79, 'Fitness', 2, 'LOWSTOCK', 3),
       (1003, 'ClBl-9831', 'Blue T-Shirt',
        'Our Blue T-Shirt is made from high-quality fabric, perfect for everyday wear.',
        'https://gebelesebeti.ge/front/asset/img/default-product.png', 29, 'Clothing', 25, 'INSTOCK', 5),
       (1004, 'AcBr-3248', 'Bracelet', 'This Bracelet features a sleek design, perfect for any occasion.',
        'https://gebelesebeti.ge/front/asset/img/default-product.png', 15, 'Accessories', 73, 'INSTOCK', 4),
       (1005, 'AcBr-5632', 'Brown Purse', 'Our Brown Purse is spacious and stylish, making it an essential accessory.',
        'https://gebelesebeti.ge/front/asset/img/default-product.png', 120, 'Accessories', 0, 'OUTOFSTOCK', 4),
       (1006, 'AcCh-4738', 'Chakra Bracelet',
        'The Chakra Bracelet is designed to balance your energy and improve well-being.',
        'https://gebelesebeti.ge/front/asset/img/default-product.png', 32, 'Accessories', 5, 'LOWSTOCK', 3),
       (1007, 'AcGa-6724', 'Galaxy Earrings',
        'Our Galaxy Earrings add a cosmic touch to your style, perfect for any occasion.',
        'https://gebelesebeti.ge/front/asset/img/default-product.png', 34, 'Accessories', 23, 'INSTOCK', 5),
       (1008, 'ElGa-8739', 'Game Controller',
        'This Game Controller offers precise control for an enhanced gaming experience.',
        'https://gebelesebeti.ge/front/asset/img/default-product.png', 99, 'Electronics', 2, 'LOWSTOCK', 4),
       (1009, 'ElGa-7285', 'Gaming Set',
        'The Gaming Set includes everything you need for an immersive gaming experience.',
        'https://gebelesebeti.ge/front/asset/img/default-product.png', 299, 'Electronics', 63, 'INSTOCK', 3),
       (1010, 'AcGo-4587', 'Gold Phone Case', 'Our Gold Phone Case provides stylish protection for your smartphone.',
        'https://gebelesebeti.ge/front/asset/img/default-product.png', 24, 'Accessories', 0, 'OUTOFSTOCK', 4),
       (1011, 'ElGr-5743', 'Green Earbuds', 'These Green Earbuds deliver high-quality sound in a compact design.',
        'https://gebelesebeti.ge/front/asset/img/default-product.png', 89, 'Electronics', 23, 'INSTOCK', 4),
       (1012, 'ClGr-3269', 'Green T-Shirt', 'The Green T-Shirt is comfortable and made from breathable materials.',
        'https://gebelesebeti.ge/front/asset/img/default-product.png', 49, 'Clothing', 74, 'INSTOCK', 5),
       (1013, 'ClGr-1346', 'Grey T-Shirt', 'Our Grey T-Shirt is a versatile piece, suitable for any casual occasion.',
        'https://gebelesebeti.ge/front/asset/img/default-product.png', 48, 'Clothing', 0, 'OUTOFSTOCK', 3),
       (1014, 'ElHe-2863', 'Headphones',
        'These Headphones offer superior sound quality with noise-cancelling features.',
        'https://gebelesebeti.ge/front/asset/img/default-product.png', 175, 'Electronics', 8, 'LOWSTOCK', 5),
       (1015, 'ClLi-9834', 'Light Green T-Shirt',
        'The Light Green T-Shirt is perfect for warm weather with its soft fabric.',
        'https://gebelesebeti.ge/front/asset/img/default-product.png', 49, 'Clothing', 34, 'INSTOCK', 4),
       (1016, 'FiLi-9283', 'Lime Band', 'Our Lime Band is perfect for fitness enthusiasts who want style and comfort.',
        'https://gebelesebeti.ge/front/asset/img/default-product.png', 79, 'Fitness', 12, 'INSTOCK', 3),
       (1017, 'ClMi-2384', 'Mini Speakers', 'These Mini Speakers provide big sound in a compact size.',
        'https://gebelesebeti.ge/front/asset/img/default-product.png', 85, 'Clothing', 42, 'INSTOCK', 4),
       (1018, 'AcPa-2384', 'Painted Phone Case', 'The Painted Phone Case combines protection with artistic design.',
        'https://gebelesebeti.ge/front/asset/img/default-product.png', 56, 'Accessories', 41, 'INSTOCK', 5),
       (1019, 'FiPi-7834', 'Pink Band', 'Our Pink Band is a stylish accessory for your fitness routine.',
        'https://gebelesebeti.ge/front/asset/img/default-product.png', 79, 'Fitness', 63, 'INSTOCK', 4),
       (1020, 'AcPi-1834', 'Pink Purse', 'The Pink Purse is compact yet spacious enough for your essentials.',
        'https://gebelesebeti.ge/front/asset/img/default-product.png', 110, 'Accessories', 0, 'OUTOFSTOCK', 4),
       (1021, 'FiPu-7392', 'Purple Band', 'The Purple Band is designed for both style and comfort during workouts.',
        'https://gebelesebeti.ge/front/asset/img/default-product.png', 79, 'Fitness', 6, 'LOWSTOCK', 3),
       (1022, 'AcPu-3284', 'Purple Gemstone Necklace',
        'This Purple Gemstone Necklace adds a touch of elegance to any outfit.',
        'https://gebelesebeti.ge/front/asset/img/default-product.png', 45, 'Accessories', 62, 'INSTOCK', 4),
       (1023, 'ClPu-4632', 'Purple T-Shirt', 'Our Purple T-Shirt is soft, comfortable, and perfect for casual wear.',
        'https://gebelesebeti.ge/front/asset/img/default-product.png', 49, 'Clothing', 2, 'LOWSTOCK', 5),
       (1024, 'ClSh-3483', 'Shoes', 'These Shoes are designed for comfort and durability.',
        'https://gebelesebeti.ge/front/asset/img/default-product.png', 64, 'Clothing', 0, 'INSTOCK', 4),
       (1025, 'ClSn-2948', 'Sneakers', 'Our Sneakers are stylish, durable, and perfect for everyday wear.',
        'https://gebelesebeti.ge/front/asset/img/default-product.png', 78, 'Clothing', 52, 'INSTOCK', 4),
       (1026, 'ClTe-7394', 'Teal T-Shirt', 'The Teal T-Shirt is a unique color option for your casual wardrobe.',
        'https://gebelesebeti.ge/front/asset/img/default-product.png', 49, 'Clothing', 3, 'LOWSTOCK', 3),
       (1027, 'ElYe-2847', 'Yellow Earbuds', 'These Yellow Earbuds offer high-quality sound with a bold design.',
        'https://gebelesebeti.ge/front/asset/img/default-product.png', 89, 'Electronics', 35, 'INSTOCK', 3),
       (1028, 'FiYo-3847', 'Yoga Mat', 'Our Yoga Mat provides excellent cushioning for your yoga practice.',
        'https://gebelesebeti.ge/front/asset/img/default-product.png', 20, 'Fitness', 15, 'INSTOCK', 5),
       (1029, 'FiYo-1829', 'Yoga Set', 'The Yoga Set includes all the essentials for your yoga routine.',
        'https://gebelesebeti.ge/front/asset/img/default-product.png', 20, 'Fitness', 25, 'INSTOCK', 5),
       (1030, 'AcRe-2483', 'Red Watch', 'This Red Watch adds a vibrant touch to your outfit.',
        'https://gebelesebeti.ge/front/asset/img/default-product.png', 75, 'Accessories', 10, 'INSTOCK', 5),
       (1031, 'ClRe-2384', 'Red T-Shirt', 'Our Red T-Shirt is a classic piece that never goes out of style.',
        'https://gebelesebeti.ge/front/asset/img/default-product.png', 29, 'Clothing', 0, 'OUTOFSTOCK', 4),
       (1032, 'AcSi-3748', 'Silver Watch', 'The Silver Watch is a sleek and modern timepiece for everyday wear.',
        'https://gebelesebeti.ge/front/asset/img/default-product.png', 65, 'Accessories', 0, 'OUTOFSTOCK', 4),
       (1033, 'ClWh-2384', 'White T-Shirt', 'Our White T-Shirt is a classic piece that pairs well with any outfit.',
        'https://gebelesebeti.ge/front/asset/img/default-product.png', 29, 'Clothing', 0, 'OUTOFSTOCK', 4),
       (1030, 'AcRe-2483', 'Red Watch', 'This Red Watch adds a vibrant touch to your outfit.',
        'https://gebelesebeti.ge/front/asset/img/default-product.png', 75, 'Accessories', 10, 'INSTOCK', 4),
       (1031, 'AcSi-6738', 'Silver Necklace', 'The Silver Necklace is a timeless piece that complements any attire.',
        'https://gebelesebeti.ge/front/asset/img/default-product.png', 150, 'Accessories', 0, 'OUTOFSTOCK', 5),
       (1032, 'AcGo-4823', 'Gold Ring', 'Our Gold Ring is an exquisite piece of jewelry perfect for special occasions.',
        'https://gebelesebeti.ge/front/asset/img/default-product.png', 200, 'Accessories', 5, 'LOWSTOCK', 5),
       (1033, 'ElSm-9834', 'Smartphone', 'This Smartphone offers the latest features and technology.',
        'https://gebelesebeti.ge/front/asset/img/default-product.png', 999, 'Electronics', 20, 'INSTOCK', 5),
       (1034, 'ElLa-3485', 'Laptop', 'Our Laptop is powerful and portable, ideal for both work and play.',
        'https://gebelesebeti.ge/front/asset/img/default-product.png', 1200, 'Electronics', 15, 'INSTOCK', 4),
       (1035, 'ElTa-4827', 'Tablet', 'This Tablet is perfect for entertainment on the go.',
        'https://gebelesebeti.ge/front/asset/img/default-product.png', 350, 'Electronics', 25, 'INSTOCK', 4),
       (1036, 'ElWi-2846', 'Wireless Mouse',
        'Our Wireless Mouse offers convenience and precision for your computer tasks.',
        'https://gebelesebeti.ge/front/asset/img/default-product.png', 50, 'Electronics', 60, 'INSTOCK', 4),
       (1037, 'ElWi-3948', 'Wireless Keyboard', 'The Wireless Keyboard provides comfort and ease of use.',
        'https://gebelesebeti.ge/front/asset/img/default-product.png', 75, 'Electronics', 45, 'INSTOCK', 4),
       (1038, 'ElMo-5739', 'Monitor', 'This Monitor delivers crystal-clear visuals for your computing needs.',
        'https://gebelesebeti.ge/front/asset/img/default-product.png', 200, 'Electronics', 18, 'INSTOCK', 4),
       (1039, 'ElPr-2984', 'Printer', 'Our Printer offers fast and high-quality prints.',
        'https://gebelesebeti.ge/front/asset/img/default-product.png', 150, 'Electronics', 5, 'LOWSTOCK', 3),
       (1040, 'ElSc-4823', 'Scanner', 'The Scanner captures high-resolution images and documents.',
        'https://gebelesebeti.ge/front/asset/img/default-product.png', 125, 'Electronics', 8, 'LOWSTOCK', 3),
       (1041, 'FuDe-3746', 'Desk Lamp', 'This Desk Lamp provides adjustable lighting for your workspace.',
        'https://gebelesebeti.ge/front/asset/img/default-product.png', 45, 'Furniture', 30, 'INSTOCK', 4),
       (1042, 'FuOf-8392', 'Office Chair', 'Our Office Chair is designed for comfort and support.',
        'https://gebelesebeti.ge/front/asset/img/default-product.png', 120, 'Furniture', 10, 'INSTOCK', 5),
       (1043, 'FuBo-4837', 'Bookshelf', 'The Bookshelf offers ample storage space for your books and decor.',
        'https://gebelesebeti.ge/front/asset/img/default-product.png', 85, 'Furniture', 5, 'LOWSTOCK', 4),
       (1044, 'FuSo-9834', 'Sofa', 'Our Sofa is comfortable and stylish, perfect for your living room.',
        'https://gebelesebeti.ge/front/asset/img/default-product.png', 750, 'Furniture', 2, 'LOWSTOCK', 5),
       (1045, 'FuCo-7342', 'Coffee Table', 'This Coffee Table is a great addition to any living space.',
        'https://gebelesebeti.ge/front/asset/img/default-product.png', 100, 'Furniture', 20, 'INSTOCK', 4),
       (1046, 'FuDi-8734', 'Dining Table', 'Our Dining Table is perfect for family meals and gatherings.',
        'https://gebelesebeti.ge/front/asset/img/default-product.png', 300, 'Furniture', 7, 'LOWSTOCK', 5),
       (1047, 'FuDi-2347', 'Dining Chair', 'The Dining Chair is comfortable and matches our dining tables.',
        'https://gebelesebeti.ge/front/asset/img/default-product.png', 75, 'Furniture', 25, 'INSTOCK', 4),
       (1048, 'FuBe-2843', 'Bed', 'Our Bed is designed for maximum comfort and a restful sleep.',
        'https://gebelesebeti.ge/front/asset/img/default-product.png', 500, 'Furniture', 4, 'LOWSTOCK', 5),
       (1049, 'FuWa-3928', 'Wardrobe', 'This Wardrobe offers spacious storage for your clothes.',
        'https://gebelesebeti.ge/front/asset/img/default-product.png', 450, 'Furniture', 6, 'LOWSTOCK', 5),
       (1050, 'FuDr-5738', 'Dresser', 'Our Dresser provides ample space for your clothing and accessories.',
        'https://gebelesebeti.ge/front/asset/img/default-product.png', 300, 'Furniture', 12, 'INSTOCK', 4),
       (1051, 'FuNi-1847', 'Nightstand', 'The Nightstand is perfect for keeping your essentials within reach.',
        'https://gebelesebeti.ge/front/asset/img/default-product.png', 85, 'Furniture', 15, 'INSTOCK', 4),
       (1052, 'ApBl-4837', 'Blender', 'This Blender is powerful and versatile, perfect for smoothies and more.',
        'https://gebelesebeti.ge/front/asset/img/default-product.png', 50, 'Appliances', 25, 'INSTOCK', 4),
       (1053, 'ApMi-3947', 'Microwave', 'Our Microwave heats your food quickly and evenly.',
        'https://gebelesebeti.ge/front/asset/img/default-product.png', 150, 'Appliances', 8, 'LOWSTOCK', 4),
       (1054, 'ApTo-7842', 'Toaster', 'This Toaster delivers perfect toast every time.',
        'https://gebelesebeti.ge/front/asset/img/default-product.png', 30, 'Appliances', 50, 'INSTOCK', 3),
       (1055, 'ApRe-2938', 'Refrigerator', 'Our Refrigerator keeps your food fresh and cool.',
        'https://gebelesebeti.ge/front/asset/img/default-product.png', 900, 'Appliances', 3, 'LOWSTOCK', 5),
       (1056, 'ApWa-4827', 'Washing Machine', 'This Washing Machine offers powerful cleaning for your laundry.',
        'https://gebelesebeti.ge/front/asset/img/default-product.png', 600, 'Appliances', 7, 'LOWSTOCK', 5),
       (1057, 'ApDr-7398', 'Dryer', 'Our Dryer is efficient and dries your clothes quickly.',
        'https://gebelesebeti.ge/front/asset/img/default-product.png', 550, 'Appliances', 10, 'INSTOCK', 4),
       (1058, 'ApDi-4937', 'Dishwasher', 'This Dishwasher makes cleaning your dishes easy and convenient.',
        'https://gebelesebeti.ge/front/asset/img/default-product.png', 700, 'Appliances', 5, 'LOWSTOCK', 5),
       (1059, 'ApAi-2738', 'Air Conditioner', 'Our Air Conditioner keeps your space cool and comfortable.',
        'https://gebelesebeti.ge/front/asset/img/default-product.png', 1200, 'Appliances', 2, 'LOWSTOCK', 5),
       (1060, 'ApHe-3947', 'Heater', 'This Heater provides warmth during the cold months.',
        'https://gebelesebeti.ge/front/asset/img/default-product.png', 250, 'Appliances', 20, 'INSTOCK', 4),
       (1061, 'ApCe-8743', 'Ceiling Fan', 'Our Ceiling Fan offers cool air circulation in any room.',
        'https://gebelesebeti.ge/front/asset/img/default-product.png', 150, 'Appliances', 15, 'INSTOCK', 4),
       (1062, 'ApVa-5732', 'Vacuum Cleaner', 'This Vacuum Cleaner provides powerful suction for clean floors.',
        'https://gebelesebeti.ge/front/asset/img/default-product.png', 300, 'Appliances', 12, 'INSTOCK', 4),
       (1063, 'ApIr-2843', 'Iron', 'Our Iron removes wrinkles from your clothes quickly and efficiently.',
        'https://gebelesebeti.ge/front/asset/img/default-product.png', 40, 'Appliances', 40, 'INSTOCK', 3),
       (1064, 'ApTo-9832', 'Toaster Oven', 'This Toaster Oven is versatile for baking, broiling, and toasting.',
        'https://gebelesebeti.ge/front/asset/img/default-product.png', 80, 'Appliances', 25, 'INSTOCK', 4),
       (1065, 'ApMi-2837', 'Mixer', 'Our Mixer makes baking and cooking easier with powerful mixing capabilities.',
        'https://gebelesebeti.ge/front/asset/img/default-product.png', 120, 'Appliances', 18, 'INSTOCK', 5),
       (1066, 'ApFo-7843', 'Food Processor', 'This Food Processor chops, slices, and dices with ease.',
        'https://gebelesebeti.ge/front/asset/img/default-product.png', 150, 'Appliances', 8, 'LOWSTOCK', 4),
       (1067, 'ApSl-4832', 'Slow Cooker', 'Our Slow Cooker prepares delicious meals with minimal effort.',
        'https://gebelesebeti.ge/front/asset/img/default-product.png', 75, 'Appliances', 12, 'INSTOCK', 4),
       (1068, 'ApRi-5938', 'Rice Cooker', 'This Rice Cooker cooks perfect rice every time.',
        'https://gebelesebeti.ge/front/asset/img/default-product.png', 60, 'Appliances', 20, 'INSTOCK', 4),
       (1069, 'ApEl-3847', 'Electric Kettle', 'Our Electric Kettle boils water quickly for your tea or coffee.',
        'https://gebelesebeti.ge/front/asset/img/default-product.png', 45, 'Appliances', 30, 'INSTOCK', 4),
       (1070, 'ApHa-2937', 'Hair Dryer', 'This Hair Dryer dries your hair quickly and gently.',
        'https://gebelesebeti.ge/front/asset/img/default-product.png', 40, 'Appliances', 25, 'INSTOCK', 3),
       (1071, 'ApCu-5739', 'Curling Iron', 'Our Curling Iron creates beautiful curls with ease.',
        'https://gebelesebeti.ge/front/asset/img/default-product.png', 35, 'Appliances', 22, 'INSTOCK', 3),
       (1072, 'ApHa-8732', 'Hair Straightener', 'This Hair Straightener gives you sleek, straight hair in minutes.',
        'https://gebelesebeti.ge/front/asset/img/default-product.png', 50, 'Appliances', 18, 'INSTOCK', 4),
       (1073, 'ApSh-9372', 'Shaver', 'Our Shaver provides a close and comfortable shave.',
        'https://gebelesebeti.ge/front/asset/img/default-product.png', 60, 'Appliances', 35, 'INSTOCK', 4),
       (1074, 'ApEl-2937', 'Electric Toothbrush', 'This Electric Toothbrush offers superior cleaning for your teeth.',
        'https://gebelesebeti.ge/front/asset/img/default-product.png', 80, 'Appliances', 15, 'INSTOCK', 5),
       (1075, 'ApSt-3847', 'Steam Iron', 'Our Steam Iron removes wrinkles and refreshes fabric with ease.',
        'https://gebelesebeti.ge/front/asset/img/default-product.png', 65, 'Appliances', 12, 'INSTOCK', 4),
       (1076, 'ApAi-2937', 'Air Purifier', 'This Air Purifier cleans the air in your home for a healthier environment.',
        'https://gebelesebeti.ge/front/asset/img/default-product.png', 200, 'Appliances', 10, 'INSTOCK', 5),
       (1077, 'ApWa-4837', 'Water Filter', 'Our Water Filter provides clean, great-tasting water.',
        'https://gebelesebeti.ge/front/asset/img/default-product.png', 90, 'Appliances', 20, 'INSTOCK', 4),
       (1078, 'AcBr-4837', 'Bracelet', 'A stylish bracelet that complements your everyday outfit.',
        'https://gebelesebeti.ge/front/asset/img/default-product.png', 20, 'Accessories', 50, 'INSTOCK', 4),
       (1079, 'FiBl-9472', 'Black Fitness Band', 'Track your fitness progress with this sleek black band.',
        'https://gebelesebeti.ge/front/asset/img/default-product.png', 35, 'Fitness', 40, 'INSTOCK', 5),
       (1080, 'ClRe-9483', 'Red Sports Shirt',
        'Stay comfortable and stylish during workouts with this red sports shirt.',
        'https://gebelesebeti.ge/front/asset/img/default-product.png', 25, 'Clothing', 70, 'INSTOCK', 4),
       (1081, 'ClGr-2839', 'Green Hoodie', 'A cozy green hoodie that is perfect for chilly days.',
        'https://gebelesebeti.ge/front/asset/img/default-product.png', 45, 'Clothing', 30, 'INSTOCK', 5),
       (1082, 'ElCa-3482', 'Camera', 'Capture stunning photos with this high-resolution camera.',
        'https://gebelesebeti.ge/front/asset/img/default-product.png', 300, 'Electronics', 15, 'INSTOCK', 5),
       (1083, 'ElHe-5938', 'Headphones', 'Experience immersive sound with these high-quality headphones.',
        'https://gebelesebeti.ge/front/asset/img/default-product.png', 75, 'Electronics', 50, 'INSTOCK', 4),
       (1084, 'FuTa-4729', 'Dining Table', 'A spacious dining table for family meals and gatherings.',
        'https://gebelesebeti.ge/front/asset/img/default-product.png', 150, 'Furniture', 20, 'INSTOCK', 4),
       (1085, 'ApVa-2857', 'Vacuum Cleaner', 'Keep your home clean with this powerful vacuum cleaner.',
        'https://gebelesebeti.ge/front/asset/img/default-product.png', 120, 'Appliances', 25, 'INSTOCK', 5),
       (1086, 'ElSm-5937', 'Smartwatch', 'A smartwatch that keeps you connected and tracks your health.',
        'https://gebelesebeti.ge/front/asset/img/default-product.png', 180, 'Electronics', 35, 'INSTOCK', 5),
       (1087, 'ElTe-4829', 'Television',
        'Enjoy your favorite shows and movies in stunning detail with this television.',
        'https://gebelesebeti.ge/front/asset/img/default-product.png', 500, 'Electronics', 10, 'INSTOCK', 5),
       (1088, 'ElRe-5827', 'Refrigerator', 'A spacious refrigerator that keeps your food fresh and cool.',
        'https://gebelesebeti.ge/front/asset/img/default-product.png', 800, 'Appliances', 12, 'INSTOCK', 4),
       (1089, 'FuSo-3746', 'Sofa', 'A comfortable sofa that adds a touch of elegance to your living room.',
        'https://gebelesebeti.ge/front/asset/img/default-product.png', 650, 'Furniture', 8, 'LOWSTOCK', 5),
       (1090, 'FiYo-2837', 'Yoga Mat', 'A non-slip yoga mat that provides comfort during your practice.',
        'https://gebelesebeti.ge/front/asset/img/default-product.png', 30, 'Fitness', 60, 'INSTOCK', 5),
       (1091, 'ClSh-4928', 'Running Shoes', 'These running shoes offer great support and cushioning.',
        'https://gebelesebeti.ge/front/asset/img/default-product.png', 70, 'Clothing', 45, 'INSTOCK', 4),
       (1092, 'ElLa-5839', 'Laptop Stand', 'A sturdy laptop stand that improves your posture and comfort.',
        'https://gebelesebeti.ge/front/asset/img/default-product.png', 40, 'Electronics', 30, 'INSTOCK', 5),
       (1093, 'ElTa-8472', 'Tablet Case', 'Protect your tablet with this durable and stylish case.',
        'https://gebelesebeti.ge/front/asset/img/default-product.png', 25, 'Electronics', 55, 'INSTOCK', 4),
       (1094, 'ApMi-5948', 'Microwave Oven', 'A microwave oven that heats and cooks your food quickly and efficiently.',
        'https://gebelesebeti.ge/front/asset/img/default-product.png', 100, 'Appliances', 20, 'INSTOCK', 4),
       (1095, 'AcRi-2837', 'Ring', 'A beautiful ring that makes a perfect gift for a loved one.',
        'https://gebelesebeti.ge/front/asset/img/default-product.png', 150, 'Accessories', 5, 'LOWSTOCK', 5),
       (1096, 'ClPa-4937', 'Pants', 'These pants offer a comfortable fit and a stylish look.',
        'https://gebelesebeti.ge/front/asset/img/default-product.png', 60, 'Clothing', 35, 'INSTOCK', 4),
       (1097, 'FuCh-5729', 'Office Chair', 'An ergonomic office chair that provides comfort during long hours of work.',
        'https://gebelesebeti.ge/front/asset/img/default-product.png', 120, 'Furniture', 18, 'INSTOCK', 5),
       (1098, 'ElKe-4938', 'Keyboard', 'A wireless keyboard that offers a comfortable typing experience.',
        'https://gebelesebeti.ge/front/asset/img/default-product.png', 50, 'Electronics', 40, 'INSTOCK', 4),
       (1099, 'AcBa-3948', 'Backpack', 'A durable and spacious backpack perfect for travel or school.',
        'https://gebelesebeti.ge/front/asset/img/default-product.png', 80, 'Accessories', 25, 'INSTOCK', 5),
       (1100, 'ClJa-5827', 'Jacket', 'A warm jacket that keeps you comfortable in cold weather.',
        'https://gebelesebeti.ge/front/asset/img/default-product.png', 90, 'Clothing', 20, 'INSTOCK', 5),
       (1101, 'ApTo-2849', 'Toaster', 'A compact toaster that delivers perfectly toasted bread every time.',
        'https://gebelesebeti.ge/front/asset/img/default-product.png', 30, 'Appliances', 30, 'INSTOCK', 4),
       (1102, 'ElSp-4938', 'Smartphone Case', 'A protective case for your smartphone that adds style and durability.',
        'https://gebelesebeti.ge/front/asset/img/default-product.png', 20, 'Electronics', 50, 'INSTOCK', 5),
       (1103, 'FuBe-5937', 'Bed Frame',
        'A sturdy bed frame that supports your mattress and enhances your bedroom decor.',
        'https://gebelesebeti.ge/front/asset/img/default-product.png', 200, 'Furniture', 10, 'INSTOCK', 4),
       (1104, 'ClHa-3847', 'Hat', 'A stylish hat that adds a finishing touch to any outfit.',
        'https://gebelesebeti.ge/front/asset/img/default-product.png', 25, 'Clothing', 50, 'INSTOCK', 5),
       (1105, 'ElEa-2839', 'Earbuds', 'High-quality earbuds that deliver clear sound and deep bass.',
        'https://gebelesebeti.ge/front/asset/img/default-product.png', 40, 'Electronics', 30, 'INSTOCK', 4),
       (1106, 'FiRu-4937', 'Running Belt', 'A convenient running belt to hold your essentials while you exercise.',
        'https://gebelesebeti.ge/front/asset/img/default-product.png', 20, 'Fitness', 60, 'INSTOCK', 5),
       (1107, 'ApCo-5729', 'Coffee Maker', 'A coffee maker that brews delicious coffee with ease.',
        'https://gebelesebeti.ge/front/asset/img/default-product.png', 100, 'Appliances', 25, 'INSTOCK', 4),
       (1108, 'AcWa-4928', 'Wallet', 'A leather wallet that is both stylish and functional.',
        'https://gebelesebeti.ge/front/asset/img/default-product.png', 50, 'Accessories', 30, 'INSTOCK', 5),
       (1109, 'ClSh-5829', 'Shirt', 'A classic shirt that is perfect for both formal and casual occasions.',
        'https://gebelesebeti.ge/front/asset/img/default-product.png', 35, 'Clothing', 40, 'INSTOCK', 4),
       (1110, 'ElHo-4837', 'Home Speaker', 'A home speaker that delivers high-quality sound throughout your space.',
        'https://gebelesebeti.ge/front/asset/img/default-product.png', 120, 'Electronics', 15, 'INSTOCK', 5),
       (1111, 'FuDi-3948', 'Dining Set', 'A complete dining set that includes a table and chairs.',
        'https://gebelesebeti.ge/front/asset/img/default-product.png', 300, 'Furniture', 8, 'LOWSTOCK', 4),
       (1112, 'ApBl-2938', 'Blender', 'A powerful blender that makes smoothies and shakes in seconds.',
        'https://gebelesebeti.ge/front/asset/img/default-product.png', 60, 'Appliances', 20, 'INSTOCK', 4),
       (1113, 'AcGl-5729', 'Glasses', 'Stylish glasses that protect your eyes and enhance your look.',
        'https://gebelesebeti.ge/front/asset/img/default-product.png', 50, 'Accessories', 25, 'INSTOCK', 5),
       (1114, 'ElMo-4838', 'Monitor Stand', 'A monitor stand that elevates your screen for better viewing comfort.',
        'https://gebelesebeti.ge/front/asset/img/default-product.png', 30, 'Electronics', 30, 'INSTOCK', 4),
       (1115, 'ClBe-4929', 'Belt', 'A durable belt that adds a finishing touch to your outfit.',
        'https://gebelesebeti.ge/front/asset/img/default-product.png', 20, 'Clothing', 50, 'INSTOCK', 5),
       (1116, 'FiEx-2847', 'Exercise Ball', 'An exercise ball that helps you strengthen your core and improve balance.',
        'https://gebelesebeti.ge/front/asset/img/default-product.png', 25, 'Fitness', 40, 'INSTOCK', 4),
       (1117, 'AcNe-3849', 'Necklace', 'A beautiful necklace that adds elegance to any outfit.',
        'https://gebelesebeti.ge/front/asset/img/default-product.png', 75, 'Accessories', 30, 'INSTOCK', 5),
       (1118, 'ApFr-4927', 'Fridge', 'A compact fridge that is perfect for small spaces.',
        'https://gebelesebeti.ge/front/asset/img/default-product.png', 250, 'Appliances', 12, 'INSTOCK', 4),
       (1119, 'ElHe-5938', 'Heater', 'A space heater that keeps your room warm and cozy.',
        'https://gebelesebeti.ge/front/asset/img/default-product.png', 80, 'Electronics', 15, 'INSTOCK', 5),
       (1120, 'ClSo-2848', 'Socks', 'Comfortable socks that keep your feet warm and dry.',
        'https://gebelesebeti.ge/front/asset/img/default-product.png', 10, 'Clothing', 100, 'INSTOCK', 4),
       (1121, 'ElDr-4937', 'Drone', 'A high-tech drone that captures stunning aerial photos and videos.',
        'https://gebelesebeti.ge/front/asset/img/default-product.png', 400, 'Electronics', 8, 'LOWSTOCK', 5),
       (1122, 'AcRi-4838', 'Ring Set', 'A set of rings that complement each other perfectly.',
        'https://gebelesebeti.ge/front/asset/img/default-product.png', 100, 'Accessories', 20, 'INSTOCK', 5),
       (1123, 'ApSt-3829', 'Stove', 'A gas stove that cooks your meals evenly and efficiently.',
        'https://gebelesebeti.ge/front/asset/img/default-product.png', 600, 'Appliances', 5, 'LOWSTOCK', 4),
       (1124, 'FuSh-5939', 'Shelf', 'A sturdy shelf that provides extra storage space for your home.',
        'https://gebelesebeti.ge/front/asset/img/default-product.png', 80, 'Furniture', 30, 'INSTOCK', 4),
       (1125, 'ElMi-4929', 'Microphone', 'A professional-grade microphone that captures clear audio.',
        'https://gebelesebeti.ge/front/asset/img/default-product.png', 150, 'Electronics', 10, 'INSTOCK', 5),
       (1126, 'ClJe-4938', 'Jeans', 'Classic jeans that offer comfort and style.',
        'https://gebelesebeti.ge/front/asset/img/default-product.png', 50, 'Clothing', 40, 'INSTOCK', 5),
       (1127, 'AcHo-2849', 'Handbag', 'A stylish handbag that is both functional and fashionable.',
        'https://gebelesebeti.ge/front/asset/img/default-product.png', 80, 'Accessories', 25, 'INSTOCK', 4),
       (1128, 'FiMa-3947', 'Mat', 'A non-slip exercise mat that provides comfort and stability.',
        'https://gebelesebeti.ge/front/asset/img/default-product.png', 25, 'Fitness', 35, 'INSTOCK', 5),
       (1129, 'ElWi-4939', 'Wireless Charger', 'A fast wireless charger that is compatible with most devices.',
        'https://gebelesebeti.ge/front/asset/img/default-product.png', 30, 'Electronics', 40, 'INSTOCK', 4),
       (1130, 'AcWa-5927', 'Wristwatch', 'A sleek wristwatch that combines style and functionality.',
        'https://gebelesebeti.ge/front/asset/img/default-product.png', 150, 'Accessories', 15, 'INSTOCK', 5),
       (1131, 'AcBr-5738', 'Leather Bracelet', 'A premium leather bracelet that adds a rugged touch to your style.',
        'https://gebelesebeti.ge/front/asset/img/default-product.png', 45, 'Accessories', 30, 'INSTOCK', 4),
       (1132, 'ClSu-4829', 'Summer Dress', 'A light and breezy summer dress, perfect for warm weather.',
        'https://gebelesebeti.ge/front/asset/img/default-product.png', 70, 'Clothing', 15, 'INSTOCK', 5),
       (1133, 'ElSp-5938', 'Speaker', 'A portable speaker with powerful sound quality.',
        'https://gebelesebeti.ge/front/asset/img/default-product.png', 120, 'Electronics', 25, 'INSTOCK', 5),
       (1134, 'AcBe-4823', 'Belt', 'A stylish belt made from high-quality materials.',
        'https://gebelesebeti.ge/front/asset/img/default-product.png', 35, 'Accessories', 40, 'INSTOCK', 4),
       (1135, 'ClSh-2937', 'Shirt', 'A crisp, button-up shirt suitable for both work and casual wear.',
        'https://gebelesebeti.ge/front/asset/img/default-product.png', 50, 'Clothing', 35, 'INSTOCK', 5),
       (1136, 'FiRu-5937', 'Resistance Bands', 'A set of resistance bands for versatile strength training.',
        'https://gebelesebeti.ge/front/asset/img/default-product.png', 25, 'Fitness', 50, 'INSTOCK', 4),
       (1137, 'ElLa-3827', 'Laptop Bag', 'A protective and stylish bag for your laptop.',
        'https://gebelesebeti.ge/front/asset/img/default-product.png', 75, 'Electronics', 20, 'INSTOCK', 5),
       (1138, 'ApBl-4829', 'Blender', 'A high-performance blender for smoothies and soups.',
        'https://gebelesebeti.ge/front/asset/img/default-product.png', 85, 'Appliances', 10, 'INSTOCK', 4),
       (1139, 'FuSo-2848', 'Sofa Bed', 'A comfortable sofa that easily converts into a bed.',
        'https://gebelesebeti.ge/front/asset/img/default-product.png', 800, 'Furniture', 5, 'LOWSTOCK', 4),
       (1140, 'ApCo-5938', 'Coffee Grinder', 'A compact coffee grinder for fresh coffee beans.',
        'https://gebelesebeti.ge/front/asset/img/default-product.png', 40, 'Appliances', 30, 'INSTOCK', 5),
       (1141, 'ElCa-4839', 'Camera Lens', 'A versatile camera lens for capturing detailed shots.',
        'https://gebelesebeti.ge/front/asset/img/default-product.png', 300, 'Electronics', 12, 'INSTOCK', 5),
       (1142, 'FiYo-3948', 'Yoga Block', 'A sturdy yoga block to assist with your yoga practice.',
        'https://gebelesebeti.ge/front/asset/img/default-product.png', 20, 'Fitness', 50, 'INSTOCK', 4),
       (1143, 'AcHo-4937', 'Handbag', 'A chic handbag, perfect for both casual and formal occasions.',
        'https://gebelesebeti.ge/front/asset/img/default-product.png', 95, 'Accessories', 20, 'INSTOCK', 5),
       (1144, 'ClSh-3947', 'Sports Shirt', 'A moisture-wicking sports shirt for active wear.',
        'https://gebelesebeti.ge/front/asset/img/default-product.png', 35, 'Clothing', 60, 'INSTOCK', 4),
       (1145, 'ElMo-4938', 'Monitor Arm', 'An adjustable monitor arm for ergonomic workspace setup.',
        'https://gebelesebeti.ge/front/asset/img/default-product.png', 55, 'Electronics', 25, 'INSTOCK', 5),
       (1146, 'FuTa-5839', 'Table', 'A versatile table that fits perfectly in any room.',
        'https://gebelesebeti.ge/front/asset/img/default-product.png', 150, 'Furniture', 20, 'INSTOCK', 4),
       (1147, 'ApMi-4829', 'Mini Microwave', 'A compact microwave perfect for small kitchens.',
        'https://gebelesebeti.ge/front/asset/img/default-product.png', 80, 'Appliances', 15, 'INSTOCK', 5),
       (1148, 'ClBe-5938', 'Beanie', 'A warm beanie to keep you cozy during cold weather.',
        'https://gebelesebeti.ge/front/asset/img/default-product.png', 20, 'Clothing', 50, 'INSTOCK', 5),
       (1149, 'AcBr-2938', 'Bracelet Set', 'A set of bracelets that complement each other for a layered look.',
        'https://gebelesebeti.ge/front/asset/img/default-product.png', 60, 'Accessories', 25, 'INSTOCK', 5),
       (1150, 'ElCh-5939', 'Charger', 'A fast charger compatible with multiple devices.',
        'https://gebelesebeti.ge/front/asset/img/default-product.png', 25, 'Electronics', 45, 'INSTOCK', 4),
       (1151, 'ApIr-4829', 'Iron', 'A lightweight iron that smoothes out wrinkles with ease.',
        'https://gebelesebeti.ge/front/asset/img/default-product.png', 35, 'Appliances', 20, 'INSTOCK', 4),
       (1152, 'ClJe-2937', 'Jeans', 'A pair of classic blue jeans with a modern fit.',
        'https://gebelesebeti.ge/front/asset/img/default-product.png', 60, 'Clothing', 40, 'INSTOCK', 5),
       (1153, 'ElTa-5839', 'Tablet', 'A compact tablet with high-resolution display.',
        'https://gebelesebeti.ge/front/asset/img/default-product.png', 400, 'Electronics', 30, 'INSTOCK', 5),
       (1154, 'FiWa-4829', 'Water Bottle', 'A reusable water bottle perfect for workouts and travel.',
        'https://gebelesebeti.ge/front/asset/img/default-product.png', 20, 'Fitness', 50, 'INSTOCK', 4),
       (1155, 'FuCo-4938', 'Coffee Table', 'A stylish coffee table with a modern design.',
        'https://gebelesebeti.ge/front/asset/img/default-product.png', 120, 'Furniture', 15, 'INSTOCK', 4),
       (1156, 'AcRi-3948', 'Ring', 'A delicate ring made with high-quality materials.',
        'https://gebelesebeti.ge/front/asset/img/default-product.png', 100, 'Accessories', 8, 'LOWSTOCK', 5),
       (1157, 'ElHe-3949', 'Headphones', 'High-fidelity headphones with noise-cancelling features.',
        'https://gebelesebeti.ge/front/asset/img/default-product.png', 200, 'Electronics', 10, 'INSTOCK', 5),
       (1158, 'ApTo-4829', 'Toaster', 'A two-slice toaster with adjustable browning settings.',
        'https://gebelesebeti.ge/front/asset/img/default-product.png', 40, 'Appliances', 30, 'INSTOCK', 4),
       (1159, 'ClSu-2937', 'Sunglasses', 'A pair of polarized sunglasses with UV protection.',
        'https://gebelesebeti.ge/front/asset/img/default-product.png', 75, 'Clothing', 20, 'INSTOCK', 5),
       (1160, 'FiFi-5838', 'Fitness Tracker', 'A fitness tracker with heart rate monitoring and GPS.',
        'https://gebelesebeti.ge/front/asset/img/default-product.png', 150, 'Fitness', 12, 'INSTOCK', 5),
       (1161, 'ElCh-4839', 'Charging Dock', 'A charging dock that can charge multiple devices simultaneously.',
        'https://gebelesebeti.ge/front/asset/img/default-product.png', 60, 'Electronics', 20, 'INSTOCK', 4),
       (1162, 'ApVa-5829', 'Vacuum Cleaner', 'A cordless vacuum cleaner with powerful suction.',
        'https://gebelesebeti.ge/front/asset/img/default-product.png', 180, 'Appliances', 10, 'INSTOCK', 5),
       (1163, 'ClTr-3948', 'Track Pants', 'Comfortable track pants for exercise and casual wear.',
        'https://gebelesebeti.ge/front/asset/img/default-product.png', 45, 'Clothing', 30, 'INSTOCK', 4),
       (1164, 'FuCh-2938', 'Chair', 'An ergonomic chair designed for maximum comfort.',
        'https://gebelesebeti.ge/front/asset/img/default-product.png', 200, 'Furniture', 15, 'INSTOCK', 5),
       (1165, 'AcNe-2937', 'Necklace', 'A beautiful necklace with a minimalist design.',
        'https://gebelesebeti.ge/front/asset/img/default-product.png', 80, 'Accessories', 25, 'INSTOCK', 4),
       (1166, 'ElWi-3938', 'Wi-Fi Router', 'A high-speed Wi-Fi router for seamless internet connection.',
        'https://gebelesebeti.ge/front/asset/img/default-product.png', 120, 'Electronics', 10, 'INSTOCK', 5),
       (1167, 'ApMi-4937', 'Mixer', 'A powerful stand mixer for baking and cooking.',
        'https://gebelesebeti.ge/front/asset/img/default-product.png', 150, 'Appliances', 12, 'INSTOCK', 5),
       (1168, 'ClJa-4837', 'Jacket', 'A waterproof jacket perfect for rainy days.',
        'https://gebelesebeti.ge/front/asset/img/default-product.png', 110, 'Clothing', 18, 'INSTOCK', 4),
       (1169, 'FiMa-4827', 'Massage Gun', 'A massage gun for deep tissue relief and muscle recovery.',
        'https://gebelesebeti.ge/front/asset/img/default-product.png', 250, 'Fitness', 8, 'LOWSTOCK', 5),
       (1170, 'ElSp-3947', 'Smartphone', 'A smartphone with cutting-edge technology and sleek design.',
        'https://gebelesebeti.ge/front/asset/img/default-product.png', 800, 'Electronics', 10, 'INSTOCK', 5),
       (1171, 'FuSh-4838', 'Bookshelf', 'A tall bookshelf with adjustable shelves for versatile storage.',
        'https://gebelesebeti.ge/front/asset/img/default-product.png', 150, 'Furniture', 5, 'LOWSTOCK', 4),
       (1172, 'ApFr-3849', 'Fridge', 'A compact fridge with energy-efficient cooling.',
        'https://gebelesebeti.ge/front/asset/img/default-product.png', 300, 'Appliances', 20, 'INSTOCK', 5),
       (1173, 'AcBe-2937', 'Belt', 'A leather belt with a classic buckle.',
        'https://gebelesebeti.ge/front/asset/img/default-product.png', 50, 'Accessories', 25, 'INSTOCK', 4),
       (1174, 'ClPa-4829', 'Pajamas', 'Comfortable pajamas made from soft cotton.',
        'https://gebelesebeti.ge/front/asset/img/default-product.png', 40, 'Clothing', 30, 'INSTOCK', 5),
       (1175, 'ElHe-5948', 'Earbuds', 'Wireless earbuds with noise-cancelling technology.',
        'https://gebelesebeti.ge/front/asset/img/default-product.png', 100, 'Electronics', 35, 'INSTOCK', 5),
       (1176, 'ApAi-3847', 'Air Fryer', 'A compact air fryer for healthy and quick meals.', 'https://gebelesebeti.ge/front/asset/img/default-product.png', 100, 'Appliances', 20, 'INSTOCK', 5),
       (1177, 'FiBl-5939', 'Balance Board', 'A balance board for improving core strength and stability.', 'https://gebelesebeti.ge/front/asset/img/default-product.png', 50, 'Fitness', 15, 'INSTOCK', 4),
       (1178, 'ElMi-2938', 'Mini Projector', 'A portable mini projector for movies and presentations on the go.', 'https://gebelesebeti.ge/front/asset/img/default-product.png', 300, 'Electronics', 10, 'INSTOCK', 5),
       (1179, 'AcHo-3948', 'Leather Handbag', 'A premium leather handbag for an elegant look.', 'https://gebelesebeti.ge/front/asset/img/default-product.png', 150, 'Accessories', 12, 'INSTOCK', 5),
       (1180, 'ClHo-4938', 'Hoodie', 'A comfortable hoodie with a modern fit.', 'https://gebelesebeti.ge/front/asset/img/default-product.png', 60, 'Clothing', 40, 'INSTOCK', 4),
       (1181, 'FuBe-5827', 'Bedside Table', 'A stylish bedside table with storage space.', 'https://gebelesebeti.ge/front/asset/img/default-product.png', 85, 'Furniture', 15, 'INSTOCK', 4),
       (1182, 'ApTo-5838', 'Toaster Oven', 'A versatile toaster oven for baking, broiling, and toasting.', 'https://gebelesebeti.ge/front/asset/img/default-product.png', 75, 'Appliances', 18, 'INSTOCK', 5),
       (1183, 'ClTr-2938', 'Trench Coat', 'A classic trench coat that never goes out of style.', 'https://gebelesebeti.ge/front/asset/img/default-product.png', 200, 'Clothing', 8, 'LOWSTOCK', 5),
       (1184, 'FiKi-4837', 'Kettlebell', 'A durable kettlebell for strength and endurance training.', 'https://gebelesebeti.ge/front/asset/img/default-product.png', 35, 'Fitness', 30, 'INSTOCK', 4),
       (1185, 'ElTa-3947', 'Tablet Stand', 'A foldable tablet stand for convenient viewing.', 'https://gebelesebeti.ge/front/asset/img/default-product.png', 25, 'Electronics', 50, 'INSTOCK', 4),
       (1186, 'ApMi-5848', 'Milk Frother', 'A handheld milk frother for making creamy lattes and cappuccinos.', 'https://gebelesebeti.ge/front/asset/img/default-product.png', 20, 'Appliances', 25, 'INSTOCK', 5),
       (1187, 'ClSh-3848', 'Shawl', 'A soft shawl that adds warmth and style.', 'https://gebelesebeti.ge/front/asset/img/default-product.png', 40, 'Clothing', 35, 'INSTOCK', 4),
       (1188, 'FuCh-5839', 'Chaise Lounge', 'A comfortable chaise lounge for relaxation.', 'https://gebelesebeti.ge/front/asset/img/default-product.png', 300, 'Furniture', 5, 'LOWSTOCK', 5),
       (1189, 'AcWa-4938', 'Wristlet', 'A compact wristlet that is perfect for carrying essentials.', 'https://gebelesebeti.ge/front/asset/img/default-product.png', 40, 'Accessories', 20, 'INSTOCK', 4),
       (1190, 'ElTv-4939', 'Smart TV', 'A smart TV with 4K resolution and streaming capabilities.', 'https://gebelesebeti.ge/front/asset/img/default-product.png', 600, 'Electronics', 15, 'INSTOCK', 5),
       (1191, 'ClSo-3849', 'Scarf', 'A cozy scarf that adds a pop of color to your outfit.', 'https://gebelesebeti.ge/front/asset/img/default-product.png', 25, 'Clothing', 45, 'INSTOCK', 4),
       (1192, 'FiRe-3948', 'Resistance Band Set', 'A set of resistance bands for a full-body workout.', 'https://gebelesebeti.ge/front/asset/img/default-product.png', 40, 'Fitness', 30, 'INSTOCK', 4),
       (1193, 'AcBa-5837', 'Leather Backpack', 'A durable leather backpack with multiple compartments.', 'https://gebelesebeti.ge/front/asset/img/default-product.png', 120, 'Accessories', 10, 'INSTOCK', 5),
       (1194, 'ApCo-2938', 'Coffee Capsule Machine', 'A coffee capsule machine for convenient brewing.', 'https://gebelesebeti.ge/front/asset/img/default-product.png', 150, 'Appliances', 12, 'INSTOCK', 4),
       (1195, 'ElMi-3947', 'Microphone', 'A professional microphone for recording high-quality audio.', 'https://gebelesebeti.ge/front/asset/img/default-product.png', 200, 'Electronics', 8, 'LOWSTOCK', 5),
       (1196, 'FuSh-4839', 'Shelving Unit', 'A modular shelving unit for customizable storage.', 'https://gebelesebeti.ge/front/asset/img/default-product.png', 150, 'Furniture', 10, 'INSTOCK', 4),
       (1197, 'ApHe-2837', 'Space Heater', 'A portable space heater for quick warmth.', 'https://gebelesebeti.ge/front/asset/img/default-product.png', 100, 'Appliances', 20, 'INSTOCK', 4),
       (1198, 'ClVe-3848', 'Vest', 'A stylish vest for layering over shirts and blouses.', 'https://gebelesebeti.ge/front/asset/img/default-product.png', 60, 'Clothing', 25, 'INSTOCK', 5),
       (1199, 'FiSt-4938', 'Stepper', 'A compact stepper for cardiovascular exercise at home.', 'https://gebelesebeti.ge/front/asset/img/default-product.png', 90, 'Fitness', 15, 'INSTOCK', 4),
       (1200, 'ElHo-3849', 'Home Theater System', 'A surround sound home theater system for an immersive experience.', 'https://gebelesebeti.ge/front/asset/img/default-product.png', 800, 'Electronics', 5, 'LOWSTOCK', 5),
       (1201, 'ApAi-4938', 'Air Purifier', 'A compact air purifier that improves indoor air quality.', 'https://gebelesebeti.ge/front/asset/img/default-product.png', 120, 'Appliances', 15, 'INSTOCK', 4),
       (1202, 'ClPa-5947', 'Palazzo Pants', 'Stylish palazzo pants that offer comfort and elegance.', 'https://gebelesebeti.ge/front/asset/img/default-product.png', 55, 'Clothing', 20, 'INSTOCK', 5),
       (1203, 'ElCa-3849', 'Camera Tripod', 'A sturdy tripod for stable camera shots.', 'https://gebelesebeti.ge/front/asset/img/default-product.png', 75, 'Electronics', 25, 'INSTOCK', 4),
       (1204, 'FiAn-3947', 'Ankle Weights', 'Adjustable ankle weights for adding resistance to workouts.', 'https://gebelesebeti.ge/front/asset/img/default-product.png', 30, 'Fitness', 50, 'INSTOCK', 5),
       (1205, 'AcBe-2938', 'Belt Bag', 'A versatile belt bag that can be worn around the waist or across the body.', 'https://gebelesebeti.ge/front/asset/img/default-product.png', 60, 'Accessories', 30, 'INSTOCK', 5),
       (1206, 'ClJa-4938', 'Jean Jacket', 'A classic jean jacket with a modern fit.', 'https://gebelesebeti.ge/front/asset/img/default-product.png', 85, 'Clothing', 15, 'INSTOCK', 4),
       (1207, 'FuBe-5837', 'Bed Frame', 'A solid bed frame that provides excellent support for your mattress.', 'https://gebelesebeti.ge/front/asset/img/default-product.png', 250, 'Furniture', 10, 'INSTOCK', 5),
       (1208, 'ElHe-2938', 'Headset', 'A gaming headset with surround sound and a built-in microphone.', 'https://gebelesebeti.ge/front/asset/img/default-product.png', 100, 'Electronics', 20, 'INSTOCK', 5),
       (1209, 'ApBl-4837', 'Blender', 'A compact blender perfect for smoothies and small batches.', 'https://gebelesebeti.ge/front/asset/img/default-product.png', 45, 'Appliances', 25, 'INSTOCK', 4),
       (1210, 'FiPi-5838', 'Pilates Ring', 'A pilates ring for resistance training and toning.', 'https://gebelesebeti.ge/front/asset/img/default-product.png', 30, 'Fitness', 35, 'INSTOCK', 5),
       (1211, 'AcGl-2939', 'Gloves', 'Warm and stylish gloves for cold weather.', 'https://gebelesebeti.ge/front/asset/img/default-product.png', 25, 'Accessories', 40, 'INSTOCK', 4),
       (1212, 'ClHo-5948', 'Hooded Sweatshirt', 'A cozy hooded sweatshirt perfect for casual wear.', 'https://gebelesebeti.ge/front/asset/img/default-product.png', 50, 'Clothing', 30, 'INSTOCK', 5),
       (1213, 'ElMo-4838', 'Monitor', 'A high-resolution monitor ideal for work and gaming.', 'https://gebelesebeti.ge/front/asset/img/default-product.png', 350, 'Electronics', 12, 'INSTOCK', 5),
       (1214, 'FuWa-3948', 'Wall Shelf', 'A decorative wall shelf for displaying your favorite items.', 'https://gebelesebeti.ge/front/asset/img/default-product.png', 60, 'Furniture', 20, 'INSTOCK', 4),
       (1215, 'ApTo-5837', 'Toaster', 'A four-slice toaster with customizable browning settings.', 'https://gebelesebeti.ge/front/asset/img/default-product.png', 70, 'Appliances', 18, 'INSTOCK', 5),
       (1216, 'ClSw-2938', 'Sweater', 'A warm and stylish sweater made from high-quality materials.', 'https://gebelesebeti.ge/front/asset/img/default-product.png', 65, 'Clothing', 22, 'INSTOCK', 5),
       (1217, 'FiRo-4839', 'Rowing Machine', 'A compact rowing machine for a full-body workout.', 'https://gebelesebeti.ge/front/asset/img/default-product.png', 450, 'Fitness', 5, 'LOWSTOCK', 5),
       (1218, 'ElCa-5947', 'Camera', 'A compact camera with advanced features for photography enthusiasts.', 'https://gebelesebeti.ge/front/asset/img/default-product.png', 400, 'Electronics', 8, 'INSTOCK', 5),
       (1219, 'AcNe-4838', 'Neck Warmer', 'A cozy neck warmer to keep you warm during winter.', 'https://gebelesebeti.ge/front/asset/img/default-product.png', 20, 'Accessories', 50, 'INSTOCK', 4),
       (1220, 'ApRe-5939', 'Rice Cooker', 'A rice cooker that ensures perfectly cooked rice every time.', 'https://gebelesebeti.ge/front/asset/img/default-product.png', 80, 'Appliances', 20, 'INSTOCK', 5),
       (1221, 'ClUn-4837', 'Underwear Set', 'A comfortable and stylish underwear set.', 'https://gebelesebeti.ge/front/asset/img/default-product.png', 30, 'Clothing', 40, 'INSTOCK', 4),
       (1222, 'FiMe-3849', 'Medicine Ball', 'A durable medicine ball for strength training.', 'https://gebelesebeti.ge/front/asset/img/default-product.png', 45, 'Fitness', 30, 'INSTOCK', 5),
       (1223, 'ElDr-3949', 'Drone', 'A high-performance drone with advanced features for aerial photography.', 'https://gebelesebeti.ge/front/asset/img/default-product.png', 700, 'Electronics', 5, 'LOWSTOCK', 5),
       (1224, 'FuDr-4938', 'Drawer Chest', 'A spacious drawer chest with a modern design.', 'https://gebelesebeti.ge/front/asset/img/default-product.png', 350, 'Furniture', 7, 'INSTOCK', 4),
       (1225, 'AcKe-2948', 'Keychain', 'A stylish keychain made from durable materials.', 'https://gebelesebeti.ge/front/asset/img/default-product.png', 15, 'Accessories', 60, 'INSTOCK', 4);

